AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'db/migrate/*.rb'
   - 'config/initializers/*.rb'
   - 'vendor/bundle/**/*'
   - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%w': '()'
